// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPaXtB8xepyW4qYDYciLLvvS7_k4eA3E',
    appId: '1:518013775568:web:66a21e198505c144e838d5',
    messagingSenderId: '518013775568',
    projectId: 'note-taker-adbb8',
    authDomain: 'note-taker-adbb8.firebaseapp.com',
    storageBucket: 'note-taker-adbb8.firebasestorage.app',
    measurementId: 'G-3NLXH7PFHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnuTaMX9Kpe0Ml8g2eo6wmNeBrCXQ-Q4',
    appId: '1:518013775568:android:1e5b57a9e63da0d0e838d5',
    messagingSenderId: '518013775568',
    projectId: 'note-taker-adbb8',
    storageBucket: 'note-taker-adbb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53ljQ8ybfHXBKiQrnMWazKmjUJKVRI2M',
    appId: '1:518013775568:ios:3ff8c9622f68c0f2e838d5',
    messagingSenderId: '518013775568',
    projectId: 'note-taker-adbb8',
    storageBucket: 'note-taker-adbb8.firebasestorage.app',
    iosBundleId: 'com.lwendo.notes.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53ljQ8ybfHXBKiQrnMWazKmjUJKVRI2M',
    appId: '1:518013775568:ios:3ff8c9622f68c0f2e838d5',
    messagingSenderId: '518013775568',
    projectId: 'note-taker-adbb8',
    storageBucket: 'note-taker-adbb8.firebasestorage.app',
    iosBundleId: 'com.lwendo.notes.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnPaXtB8xepyW4qYDYciLLvvS7_k4eA3E',
    appId: '1:518013775568:web:4f4ffbcb1008b2d2e838d5',
    messagingSenderId: '518013775568',
    projectId: 'note-taker-adbb8',
    authDomain: 'note-taker-adbb8.firebaseapp.com',
    storageBucket: 'note-taker-adbb8.firebasestorage.app',
    measurementId: 'G-PZ9FMJXBJV',
  );
}
